import type { TourStep } from "@/components/onboarding/tour-overlay";
import type { OnboardingPageKey } from "@/lib/onboarding-pages";

export const PAGE_TOUR_STEPS: Record<OnboardingPageKey, TourStep[]> = {
  dashboard: [
    {
      id: "dashboard-1",
      target: null,
      title: "Dashboard mission",
      body: "This is the working surface for daily pricing, UPC, and listing review. Search first, stage changes second, and only push after the review confirms the plan.",
    },
    {
      id: "dashboard-2",
      target: "dashboard-connection",
      title: "Connection status",
      body: "Check this before trusting what you see. If the app is not connected to live database data, stop and fix that first before making pricing decisions.",
    },
    {
      id: "dashboard-3",
      target: "dashboard-health-banner",
      title: "Store update health",
      body: "When this banner appears, one or more stores are behind on pulls or webhook follow-up. Use the next-step message here as your shortcut into Sync or Errors.",
    },
    {
      id: "dashboard-4",
      target: "dashboard-search",
      title: "Search and jump",
      body: "Search by SKU, title, UPC, or marketplace item ID. This is the fastest way to move from an external issue report to the exact row you need to fix.",
    },
    {
      id: "dashboard-5",
      target: "dashboard-filters",
      title: "Filter the workload",
      body: "Use store, stock, staged-only, and missing-data filters to narrow the table to the kind of work you are doing right now.",
    },
    {
      id: "dashboard-6",
      target: "dashboard-toolbar",
      title: "Bulk tools bar",
      body: "This top bar holds the big operational tools: bulk UPC matching, global price updates, staged cleanup, failed push review, column control, and export.",
    },
    {
      id: "dashboard-7",
      target: "dashboard-global-price",
      title: "Global price update",
      body: "Use this when you want to copy a pricing rule across many rows at once. It is best for controlled pricing campaigns, not one-off fixes.",
    },
    {
      id: "dashboard-8",
      target: "dashboard-staged-tools",
      title: "Staged workbench",
      body: "This area helps you manage in-progress changes. Review failed pushes, inspect what is still staged, and clear staged values only when you truly want to discard them.",
    },
    {
      id: "dashboard-9",
      target: "dashboard-columns-export",
      title: "View and export controls",
      body: "Columns lets you tune the table for the task at hand, and Export gives you a spreadsheet snapshot of the current view for audit or offline review.",
    },
    {
      id: "dashboard-10",
      target: "dashboard-grid",
      title: "Read the row layout",
      body: "Each row groups one SKU family. Frozen columns keep identity visible on the left, while store blocks on the right show live values, staged changes, and push actions per marketplace.",
    },
    {
      id: "dashboard-11",
      target: "dashboard-header-frozen",
      title: "Frozen identity columns",
      body: "UPC, item IDs, SKU, and title stay visible while you scroll. That lets you edit price, ad rate, and profit without losing row identity.",
    },
    {
      id: "dashboard-12",
      target: "dashboard-header-sale-price",
      title: "Price workflow",
      body: "Sale Price is the main operational column. Edit one store, set all stores, review push, or fast push depending on how much confirmation the change deserves.",
    },
    {
      id: "dashboard-13",
      target: "dashboard-header-profit",
      title: "Profit check",
      body: "Always finish by checking the profit column after pricing or fee changes. The point is not just to update a number, but to keep the row commercially valid.",
    },
  ],
  sync: [
    {
      id: "sync-1",
      target: "sync-header",
      title: "Sync page purpose",
      body: "This page pulls marketplace data into reorG. It is pull-only, so nothing here sends price or UPC changes back out to the stores.",
    },
    {
      id: "sync-2",
      target: "sync-pull-only",
      title: "Safety boundary",
      body: "Use Sync freely when you need fresher marketplace data. It updates reorG's live snapshot but does not push staged edits to any marketplace.",
    },
    {
      id: "sync-3",
      target: "sync-actions",
      title: "Global actions",
      body: "Sync All is your broad refresh button. Use it after outages, major credential repairs, or when several stores need a manual pull at once.",
    },
    {
      id: "sync-4",
      target: "sync-scheduler",
      title: "Automatic background updates",
      body: "This panel tells you whether automation is healthy: what happened at the last check, how many stores were ready, and whether the scheduler is currently keeping up.",
    },
    {
      id: "sync-5",
      target: "sync-freshness",
      title: "Store freshness diagnostics",
      body: "These cards explain why a store is healthy, delayed, or needs attention. Use this before retrying blindly so you know whether the issue is stale pulls, quiet webhooks, or something else.",
    },
    {
      id: "sync-6",
      target: "sync-jobs",
      title: "Recent scheduled jobs",
      body: "Review the latest automated pulls here. This gives you proof of whether the system is completing on schedule and what each store's last mode and result were.",
    },
    {
      id: "sync-7",
      target: "sync-upcoming",
      title: "What happens next",
      body: "This panel answers the operational question, 'Do I wait or intervene?' If a store is already due or queued, let automation work. If it stays behind, run a manual pull.",
    },
    {
      id: "sync-8",
      target: "sync-webhooks",
      title: "Recent marketplace notices",
      body: "Webhook events show whether the stores are still sending change signals into reorG. Healthy webhooks can wake up an earlier targeted refresh between normal scheduled pulls.",
    },
    {
      id: "sync-9",
      target: "sync-automation-events",
      title: "Why the system acted",
      body: "Automation events explain starts, skips, cooldowns, stale-job cleanup, and other scheduler decisions. Use them when the system's behavior seems surprising.",
    },
    {
      id: "sync-10",
      target: "sync-stores",
      title: "Per-store action cards",
      body: "Each store card is where you manually intervene. Check last result, next pull time, cooldown status, webhook health, and then choose Sync Now or Full Sync for that store only.",
    },
    {
      id: "sync-11",
      target: "sync-stores",
      title: "Sync Now vs Full Sync",
      body: "Sync Now uses the store's default sync mode. Full Sync forces the heaviest refresh path for that store and is best when the lighter path did not clear the issue.",
    },
  ],
  integrations: [
    {
      id: "integrations-1",
      target: "integrations-header",
      title: "Integration control center",
      body: "This page manages marketplace connectivity, credentials, store identity, and per-store write safety. Treat it as the wiring panel for the rest of the app.",
    },
    {
      id: "integrations-2",
      target: "integrations-header",
      title: "Connection coverage",
      body: "The connection count at the top quickly tells you whether the app is fully wired up or still missing one or more stores.",
    },
    {
      id: "integrations-3",
      target: "integrations-global-lock",
      title: "Per-store locks vs global lock",
      body: "Per-integration write locks stop pushes for one store only. If you need to freeze all marketplace writes, use the global safety controls on Settings.",
    },
    {
      id: "integrations-4",
      target: "integrations-cards",
      title: "Store identity and credentials",
      body: "Use the cards to confirm each store is the correct account, reconnect credentials, and test the connection before trusting item IDs or live data.",
    },
    {
      id: "integrations-5",
      target: "integrations-cards",
      title: "Write readiness",
      body: "These same cards control whether a store is enabled for operational use and whether writes are locked. This is where you isolate one store without shutting down the whole app.",
    },
    {
      id: "integrations-6",
      target: "integrations-cards",
      title: "Master-store awareness",
      body: "Pay attention to master-store labels here. Matching, row identity, and some fallback assumptions depend on which store is acting as the master source.",
    },
  ],
  engineRoom: [
    {
      id: "engine-1",
      target: "engine-header",
      title: "Engine Room purpose",
      body: "Engine Room is the forensic side of reorG. Come here when you need job history, raw operational context, or proof of what happened and when.",
    },
    {
      id: "engine-2",
      target: "engine-summary",
      title: "Summary cards",
      body: "The summary row gives you the fastest read on system pressure: active syncs, queued pushes, recent failures, store update health, and write lock state.",
    },
    {
      id: "engine-3",
      target: "engine-active-syncs",
      title: "Active sync load",
      body: "Use this card to see whether sync work is currently in flight. It helps explain why data may still be catching up or why a store refresh is taking time.",
    },
    {
      id: "engine-4",
      target: "engine-recent-errors",
      title: "Recent failures",
      body: "This card is historical, not only current. It tells you whether the system has been unstable lately even if the dashboard happens to look healthy right now.",
    },
    {
      id: "engine-5",
      target: "engine-write-lock",
      title: "Write lock status",
      body: "This is the safety checkpoint for outbound marketplace writes. Pulls and diagnostics can still run while the lock is on, but pushes should not.",
    },
    {
      id: "engine-6",
      target: "engine-scheduler",
      title: "Scheduler health",
      body: "Review due counts, dispatch timing, and automation health here when stores fall behind. This is the best place to tell whether the scheduler itself is the issue.",
    },
    {
      id: "engine-7",
      target: "engine-tabs",
      title: "Pick the right tab",
      body: "Use Sync Jobs for inbound pulls, Push Jobs and Queue for outbound work, Change Log for edits, and Raw Events when you need low-level traces.",
    },
    {
      id: "engine-8",
      target: "engine-table",
      title: "Read the evidence",
      body: "The tables show status, timestamps, counts, categories, and recommended actions. This is where you turn a vague complaint into a specific operational answer.",
    },
  ],
  errors: [
    {
      id: "errors-1",
      target: "errors-header",
      title: "Errors page role",
      body: "This page translates raw failures into grouped operational issues. It is the fastest way to see what is broken without reading low-level logs first.",
    },
    {
      id: "errors-2",
      target: "errors-filters",
      title: "Filter before triage",
      body: "Start by narrowing severity, root cause, store, and time range. That keeps you from mixing old noise with the issue you are trying to resolve right now.",
    },
    {
      id: "errors-3",
      target: "errors-list",
      title: "Grouped issue cards",
      body: "Issues are grouped by problem type so you can clear one queue at a time instead of bouncing between unrelated failures.",
    },
    {
      id: "errors-4",
      target: "errors-list",
      title: "Recommended action",
      body: "Every card tries to tell you where to go next. Follow that route first before guessing, because many issues already point directly to Sync, Integrations, or Engine Room.",
    },
    {
      id: "errors-5",
      target: "errors-list",
      title: "Dismiss with care",
      body: "Dismiss only hides the symptom from the current list. If the root cause is still present, the issue will come back the next time the system detects it.",
    },
  ],
  unmatched: [
    {
      id: "unmatched-1",
      target: "unmatched-header",
      title: "Why unmatched exists",
      body: "These are marketplace listings that reorG could not connect to a master SKU automatically. Until they are linked, they stay out of the main dashboard row model.",
    },
    {
      id: "unmatched-2",
      target: "unmatched-filters",
      title: "Process in batches",
      body: "Filter by store or search by SKU and title so you can work one clean batch at a time instead of mixing unrelated unmatched listings together.",
    },
    {
      id: "unmatched-3",
      target: "unmatched-list",
      title: "Manual link workflow",
      body: "Use manual matching when you know the correct master SKU. This is the step that turns a loose marketplace listing into a row that can be priced and reviewed normally.",
    },
    {
      id: "unmatched-4",
      target: "unmatched-list",
      title: "Ignore vs fix",
      body: "Ignore is for noise, test data, or listings you intentionally do not want in the row model. Do not use ignore as a shortcut when the listing really needs to be matched.",
    },
    {
      id: "unmatched-5",
      target: "unmatched-list",
      title: "Verify the result",
      body: "After matching, confirm the listing leaves this queue and appears correctly on the dashboard under the intended SKU family.",
    },
  ],
  import: [
    {
      id: "import-1",
      target: "import-header",
      title: "Import page purpose",
      body: "This page is for structured spreadsheet updates into reorG's internal fields, such as supplier cost, shipping inputs, and other workbook-driven data.",
    },
    {
      id: "import-2",
      target: "import-steps",
      title: "Follow the import stages",
      body: "The step rail keeps the import safe: upload, preview, choose the mode, confirm the write, then review the result. Use the sequence instead of jumping ahead.",
    },
    {
      id: "import-3",
      target: "import-result",
      title: "Preview before apply",
      body: "The preview is where you catch bad headers, missing SKUs, or unexpected overwrites. Fix the file first, then rerun the import instead of trying to correct mistakes afterward.",
    },
    {
      id: "import-4",
      target: "import-result",
      title: "Choose the right mode",
      body: "Fill blanks is safer for onboarding or enrichment. Overwrite is for controlled corrections where you intentionally want the workbook to replace what is already stored.",
    },
    {
      id: "import-5",
      target: "import-result",
      title: "Close the loop",
      body: "After the import, review the created and updated counts, note any row-level failures, and spot-check the affected fields on the dashboard.",
    },
  ],
  shippingRates: [
    {
      id: "shipping-1",
      target: "shipping-header",
      title: "Why shipping rates matter",
      body: "These rate tiers feed directly into dashboard shipping cost and profit calculations. A bad tier here quietly distorts every row that uses it.",
    },
    {
      id: "shipping-2",
      target: "shipping-table",
      title: "Edit only what changed",
      body: "Treat the table like a controlled pricing input. Update the exact brackets that changed in the carrier sheet rather than retyping everything each time.",
    },
    {
      id: "shipping-3",
      target: "shipping-save",
      title: "Save, then validate",
      body: "After saving, return to the dashboard and spot-check representative light, medium, and heavy SKUs so profit still looks correct.",
    },
  ],
  backups: [
    {
      id: "backups-1",
      target: "backups-header",
      title: "Backup strategy",
      body: "This page tracks the snapshots that protect you before risky operations. Use it as your confidence check before wide pushes or large imports.",
    },
    {
      id: "backups-2",
      target: "backups-actions",
      title: "Manual backup actions",
      body: "Create a manual backup when the upcoming work deserves its own restore point instead of relying only on the normal automatic cadence.",
    },
    {
      id: "backups-3",
      target: "backups-list",
      title: "Read the backup history",
      body: "Check status, size, coverage, and expiry so you know whether the backup is usable and whether the recovery window is long enough for the operation you are planning.",
    },
    {
      id: "backups-4",
      target: "backups-list",
      title: "Use downloads intentionally",
      body: "JSON and spreadsheet downloads are useful for audit, offline review, and recovery planning, even when you are not doing a live restore.",
    },
  ],
  setup: [
    {
      id: "setup-1",
      target: "setup-header",
      title: "Setup checklist purpose",
      body: "This page is the go-live and health-readiness checklist. It tells you what is truly ready, what still needs work, and what should block risky operations.",
    },
    {
      id: "setup-2",
      target: "setup-steps",
      title: "Read the statuses",
      body: "Use the status labels to prioritize in the right order. Anything marked Needs Attention should be treated as a blocker until it is understood and resolved.",
    },
    {
      id: "setup-3",
      target: "setup-steps",
      title: "Use it as a release gate",
      body: "Before imports, large pushes, or team handoff, scan this page first. It is the quickest way to catch regressions in connectivity, safety, or data quality.",
    },
    {
      id: "setup-4",
      target: "setup-steps",
      title: "Think operationally",
      body: "This checklist is not just onboarding. Revisit it after major changes so you know whether the system is still safe and predictable for daily operations.",
    },
  ],
  users: [
    {
      id: "users-1",
      target: "users-header",
      title: "Users page purpose",
      body: "This page controls who can access reorG and what operational responsibility sits with each account.",
    },
    {
      id: "users-2",
      target: "users-profile",
      title: "My account",
      body: "Use this section to keep your own profile and password current. Good account hygiene matters because this app controls real marketplace operations.",
    },
    {
      id: "users-3",
      target: "users-manage",
      title: "Manage team access",
      body: "Admins can create, review, and manage user access here. Treat this as the gatekeeper for who can reach pricing, sync, and write controls.",
    },
    {
      id: "users-4",
      target: "users-manage",
      title: "Auditability",
      body: "Use the roster and recent actions to answer who had access and who changed what when you are reviewing an incident or onboarding a teammate.",
    },
  ],
  settings: [
    {
      id: "settings-1",
      target: "settings-header",
      title: "Settings overview",
      body: "Settings mixes personal workspace preferences with global safety controls. Some changes affect only your view; others affect live operational risk.",
    },
    {
      id: "settings-2",
      target: "settings-display",
      title: "Display preferences",
      body: "Theme, density, row height, and text size let each user tune the dashboard for speed and readability without changing shared business data.",
    },
    {
      id: "settings-3",
      target: "settings-safety",
      title: "Global safety controls",
      body: "This is where you control the broadest write protections, including the switches that can block marketplace pushes across the app.",
    },
    {
      id: "settings-4",
      target: "settings-tour",
      title: "Tour controls",
      body: "Replay tours after layout changes or reset them when you want the team to re-onboard against the current UI.",
    },
    {
      id: "settings-5",
      target: "settings-tour",
      title: "Use tours as documentation",
      body: "The page tours are now part of the operational docs. When the UI changes meaningfully, this is where you keep onboarding aligned with the real app.",
    },
  ],
};
